import {makeLevel} from './engine.mjs';
import {PALETTE,cubeSVG} from './render.mjs';
export const VERSION='1.0.0';
const ICONS={
 play:'<path d="M18 9L53 32 18 55Z" fill="#eaffca" stroke="#184313" stroke-width="4" stroke-linejoin="round"/>',
 back:'<path d="M43 12L20 32l23 20M21 32h33" fill="none" stroke="#f1ffd8" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>',
 pause:'<path d="M18 11v42M43 11v42" stroke="#fff8a6" stroke-width="12"/>',
 retry:'<path d="M49 23a22 22 0 1 0 3 21" fill="none" stroke="#f1ffd6" stroke-width="8" stroke-linecap="round"/><path d="M37 24l18 5-2-19" fill="#eeffd0" stroke="#1e5716" stroke-width="2"/>',
 home:'<path d="M8 28L32 8l24 20M16 25v30h32V25" fill="#efffd6" stroke="#1c5217" stroke-width="5" stroke-linejoin="round"/><path d="M27 39h10v16H27Z" fill="#438b18"/>',
 create:'<path d="M11 8h15v16H11zm27 0h15v16H38zM11 38h15v16H11zm27 0h15v16H38z" fill="#eaffd6" stroke="#234f12" stroke-width="3"/><path d="M29 24h7v17h-7zM24 29h17v7H24z" fill="#ffffb1"/>',
 settings:'<path d="M26 4h12l2 10 9 4 9-2 6 11-8 8-2 10 3 8-11 7-9-6-10-1-9 5-9-9 5-9-2-11-8-5 4-12 11 1z" transform="translate(1 1) scale(.92)" fill="#efffcf" stroke="#204d17" stroke-width="3"/><circle cx="32" cy="32" r="10" fill="#4aa81c" stroke="#225217" stroke-width="3"/>',
 stats:'<path d="M17 8h30v16c0 11-7 18-15 18S17 35 17 24zM17 14H8v8c0 9 9 12 14 12m25-20h9v8c0 9-9 12-14 12M32 42v12M19 56h26" fill="#fff0a5" stroke="#586411" stroke-width="4" stroke-linejoin="round"/>',
 info:'<circle cx="32" cy="14" r="5" fill="#f1ffce"/><path d="M25 29h8v23h8M23 54h21" fill="none" stroke="#f1ffce" stroke-width="8"/>',
 arrow:'<path d="M15 7L49 32 15 57l5-25z" fill="#95fcf0" stroke="#062847" stroke-width="4" stroke-linejoin="round"/>'
};
const svg=name=>`<svg viewBox="0 0 64 64" aria-hidden="true">${ICONS[name]||ICONS.play}</svg>`;
const round=(action,icon,label,extra='')=>`<button class="round ${extra}" data-action="${action}" aria-label="${label}" title="${label}">${svg(icon)}</button>`;
const back=()=>round('back','back','Back','back');
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderView(){
 this.shell.classList.toggle('no-motion',this.settings.reducedMotion);let html='';
 if(this.screen==='menu')html=`<div class="topline"><span class="brand-mini"><i class="mini-box"></i>GEOMETRYLITE.NET</span><span>ORIGINAL WEB EDITION</span></div><div class="screen"><div class="tag">NO DOWNLOAD · NO IFRAME</div><h1 class="title outlined">GEOMETRY<span class="lite">LITE</span></h1><div class="main-actions"><div><button class="tile cube" data-action="icons" aria-label="Customize character">${cubeSVG(...this.colors,this.settings.icon)}</button><span class="action-label">CUSTOMIZE</span></div><div>${round('choose','play','Choose a level','big')}</div><div><button class="tile" data-action="editor" aria-label="Level editor">${svg('create')}</button><span class="action-label">CREATE</span></div></div><div class="small-actions">${round('settings','settings','Settings')}${round('stats','stats','My progress')}${round('about','info','How to play')}</div><div class="keys"><span class="keycap">SPACE</span> / CLICK / TAP TO JUMP<br><button class="subtle" data-action="watch">Watch a full level ↗</button></div></div><div class="bottomline"><span>ONE TOUCH. PURE RHYTHM.</span><span>NATIVE ${VERSION}</span></div>`;
 if(this.screen==='levels'){const l=this.level,s=this.store.stats[this.index];html=`${back()}<div class="screen"><div class="level-wrap"><button class="arrows prev" data-action="prev" aria-label="Previous level">${svg('arrow')}</button><div class="level-card"><div class="level-top"><div class="difficulty"><span class="difficulty-face">${this.index===2?'›‹':'⌣'}</span><span>${l.difficulty}<small>LEVEL ${this.index+1} / 3</small></span></div><span class="stars">${l.stars} ★</span></div><h2 class="level-name outlined">${l.name}</h2><div class="subtitle">${l.subtitle}</div>${this.records()}${this.coins(s.coins)}<div class="level-controls"><button class="green" data-action="play">▶ PLAY</button><button class="blue" data-action="practice">◆ PRACTICE</button></div><div class="track">♫ <b>${l.name}</b> · Original soundtrack · ${l.bpm} BPM · ${Math.round(l.duration)} sec</div></div><button class="arrows next" data-action="next" aria-label="Next level">${svg('arrow')}</button><div class="dots">${[0,1,2].map(i=>`<span class="dot ${this.index===i?'active':''}"></span>`).join('')}</div><button class="subtle" data-action="watch">Watch preview · does not set records</button></div></div>`;}
 if(this.screen==='settings')html=`${back()}<div class="screen"><div class="panel"><h2 class="outlined">SETTINGS</h2>${[['music','Music volume'],['sfx','Sound effects']].map(([k,l])=>`<label class="settings-row"><span>${l}<small data-value="${k}">${Math.round(this.settings[k]*100)}%</small></span><input aria-label="${l}" type="range" min="0" max="1" step=".01" data-setting="${k}" value="${this.settings[k]}"></label>`).join('')}${[['autoRetry','Auto retry','Restart quickly after a crash'],['particles','Particles & trails','Cube sparks, flight trails and portal effects'],['reducedMotion','Reduced motion','Disable screen shake and flashes']].map(([k,l,d])=>`<label class="settings-row"><span>${l}<small>${d}</small></span><input type="checkbox" data-setting="${k}" ${this.settings[k]?'checked':''} aria-label="${l}"></label>`).join('')}<button class="green" data-action="back">DONE</button></div></div>`;
 if(this.screen==='icons')html=`${back()}<div class="screen"><div class="panel"><h2 class="outlined">MAKE IT YOURS</h2><div class="preview-icon">${cubeSVG(...this.colors,this.settings.icon)}</div><div class="icons-grid">${[0,1,2,3,4,5].map(i=>`<button class="icon-choice ${i===this.settings.icon?'active':''}" data-action="icon:${i}" aria-label="Icon ${i+1}" aria-pressed="${i===this.settings.icon}">${cubeSVG(...this.colors,i)}</button>`).join('')}</div>${[['primary','PRIMARY COLOR'],['secondary','SECONDARY COLOR']].map(([k,l])=>`<div class="tag">${l}</div><div class="swatches">${PALETTE.map((p,i)=>`<button class="swatch ${this.settings[k]===i?'active':''}" style="--swatch:${p}" data-action="${k}:${i}" aria-label="${k} color ${i+1}" aria-pressed="${this.settings[k]===i}"></button>`).join('')}</div>`).join('')}<button class="green" data-action="back">LOOKING GOOD</button></div></div>`;
 if(this.screen==='stats')html=`${back()}<div class="screen"><div class="panel"><h2 class="outlined">YOUR PROGRESS</h2><div class="stat-grid"><div><b>${this.store.stats.filter(s=>s.best===100).length}/3</b><span>LEVELS COMPLETE</span></div><div><b>${this.store.stats.reduce((a,s)=>a+s.attempts,0)}</b><span>ATTEMPTS</span></div><div><b>${this.store.totalJumps}</b><span>JUMPS</span></div></div>${[0,1,2].map(i=>`<div class="stat-row"><span>${makeLevel(i).name}</span><b>${this.store.stats[i].best}%</b></div>`).join('')}<p>Normal and practice records are separate.<br>Watch mode never changes your records.</p><button class="green" data-action="back">KEEP GOING</button></div></div>`;
 if(this.screen==='about')html=`${back()}<div class="screen"><div class="panel"><h2 class="outlined">FIND YOUR RHYTHM</h2><div class="help-grid"><b>SPACE / ↑ / CLICK / TAP</b><span>Jump. Hold to jump again on landing.</span><b>SHIP</b><span>Hold to climb. Release to descend.</span><b>WAVE</b><span>Hold to go up. Release to go down.</span><b>YELLOW ORB</b><span>Tap again while overlapping the ring.</span><b>PRACTICE · Z / X</b><span>Place / remove a checkpoint on safe ground.</span><b>ESC · R · M · F</b><span>Pause · retry · mute · fullscreen.</span></div><p>Original levels, graphics and synthesized music, made for GeometryLite. An independent rhythm platformer, not an official Geometry Dash release or affiliated with RobTop Games.</p><button class="green" data-action="back">LET'S GO</button></div></div>`;
 if(['game','pause','result'].includes(this.screen)){
  html=`<div class="hud"><div class="hud-top"><span class="run-label ${this.watch?'watch':this.practice?'practice':''}">${this.watch?'WATCH MODE<br>NO RECORDS':this.practice?'PRACTICE MODE':escapeHTML(this.level.name.toUpperCase())}</span><div class="progress-wrap"><div class="progress-fill"></div></div><span class="percentage">0%</span><button class="pause-button" data-action="pause" aria-label="Pause">${svg('pause')}</button></div><div class="hud-bottom"><div class="hud-tools"><button data-action="mute" aria-label="Toggle audio">${this.settings.muted?'SOUND OFF':'♫ SOUND'}</button><button data-action="fullscreen">FULLSCREEN</button><button data-action="screenshot" aria-label="Save game screenshot">▣</button>${this.practice?'<button data-action="checkpoint">◆ Z</button><button data-action="remove-checkpoint">✕ X</button>':''}</div><span>SPACE / CLICK / TAP ${this.world?.mode==='cube'?'TO JUMP':'AND HOLD'}</span>${this.coins(this.world?.coins||0,true)}</div></div>`;
  if(this.screen==='pause')html+=`<div class="screen paused"><div class="panel"><h2 class="pause-title outlined">PAUSED</h2><p>${escapeHTML(this.level.name)} · ${Math.floor(this.world.t/this.level.duration*100)}% · Attempt ${this.attempt}</p>${this.customRun?'':this.records()}<div class="pause-actions">${round('home','home',this.customRun?'Back to editor':'Level select')}${round('resume','play','Resume')}${round('retry','retry','Restart')}</div><button class="mode-button" data-action="toggle-practice">${this.practice?'◆ PRACTICE MODE · switch to normal':'◇ NORMAL MODE · switch to practice'}</button></div></div>`;
  if(this.screen==='result')html+=`<div class="screen paused"><div class="panel"><h2 class="outlined result-title">${this.watch?'PREVIEW COMPLETE':this.practice?'PRACTICE COMPLETE':'LEVEL COMPLETE!'}</h2><div class="result-percent outlined">100%</div>${this.coins(this.world.coins)}<p>${escapeHTML(this.level.name)} · ${this.attempt} attempt${this.attempt===1?'':'s'}<br>${this.watch?'Preview uses normal collisions. No records were changed.':this.practice?'Practice progress saved. Normal record unchanged.':'Every jump brought you here.'}</p><div class="level-controls"><button class="blue" data-action="home">${this.customRun?'EDITOR':'LEVELS'}</button><button class="green" data-action="retry">PLAY AGAIN</button></div></div></div>`;
  if(this.starting)html+='<div class="loading">GET READY…</div>';
 }
 if(this.screen==='editor')html=`<div class="editor-toolbar"><div><button class="edit-btn secondary" data-action="back" aria-label="Exit editor">◀</button><input class="editor-name" aria-label="Level name" data-editor="name" maxlength="32" value="${escapeHTML(this.custom.name)}"><button class="edit-btn" data-action="editor-play">▶ TEST</button><button class="edit-btn" data-action="editor-save">SAVE</button></div><div><button class="edit-btn secondary" data-action="editor-undo" aria-label="Undo">↶</button><button class="edit-btn secondary" data-action="editor-redo" aria-label="Redo">↷</button><button class="edit-btn secondary" data-action="editor-export">EXPORT</button><button class="edit-btn secondary" data-action="editor-import">IMPORT</button><button class="edit-btn secondary" data-action="editor-clear">CLEAR</button></div></div><div class="editor-bottom"><div class="palette">${[['block','■','BLOCK'],['spike','▲','SPIKE'],['saw','✹','SAW'],['orb','◎','ORB'],['pad','⌒','PAD'],['coin','★','COIN'],['erase','×','ERASE']].map(([k,s,l])=>`<button class="${this.tool===k?'selected':''}" data-action="tool:${k}" aria-label="${l}"><b>${s}</b>${l}</button>`).join('')}</div><div class="editor-pan"><span>SCROLL</span><input type="range" min="0" max="${this.custom.duration*this.custom.speed-W}" step="40" value="${this.editorX}" data-editor="pan" aria-label="Scroll level"><span data-count>${this.custom.objects.length} objects</span></div></div>`;
 this.ui.innerHTML=html;this.updateHUD();
}
